packages:
  - apps/*
  - packages/*
minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.5.10'
  - '@storybook/builder-vite@10.5.10'
  - '@storybook/csf-plugin@10.5.10'
  - '@storybook/svelte-vite@10.5.10'
  - '@storybook/svelte@10.5.10'
  - storybook@10.5.10
